<?php 
$user = Default_Model_UserObject::getUserObject();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<?=$this->headTitle()?>	
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/bootstrap_united.css')?>
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/bootstrap-responsive.min.css')?>
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/site.css')?>
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/anytime.css')?>
	<?="" /** $this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/ui-lightness/jquery-ui-1.8.21.custom.css') **/?>
	<?="" /**$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/smoothness/jquery-ui-1.10.1.custom.css') **/?>
	<?=""/**$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/redmond/jquery-ui-1.10.1.custom.css')**/?>
	<?="" /** $this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/cupertino/jquery-ui.min.css') **/?>
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/cupertino/jquery-ui.css')?>
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/jqueryui/le-frog/jquery-ui-isms.css')?>
	
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/ui.jqgrid.css')?>	
	<?=$this->headLink()->appendStylesheet('/'.Default_Model_Base::WEB_ROOT_TXT.'/css/ui.daterangepicker.css')?>
		
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jquery.js"></script>
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jquery-ui-1.8.21.custom.min.js"></script>
    
    <!--
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jquery-ui-1.10.1.custom.js"></script>    
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/fix_jqueryui_ckeditor.js"></script>
      -->
    
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jsrender.js"></script>    
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/bootstrap.js"></script>
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/modernizr.js"></script>    
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/anytime.js"></script>
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/date.js"></script>  
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/daterangepicker.jQuery.js"></script>  
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/i18n/grid.locale-tw.js"></script>
    <!--
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jquery.jqGrid.min.js"></script>
    -->
    <script src="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/js/jquery.jqGrid.src.js"></script>  
    
          	
</head>

<body>	
    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          	<a class="brand" href="<?=Default_Model_Base::WEB_ROOT?>">資安管理系統</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="">
						<a href="<?=Default_Model_Base::WEB_ROOT?>business/edit">業務衝擊分析</a>
					</li>
					<li class="">
						<a href="<?=Default_Model_Base::WEB_ROOT?>asset/edit">資產管理</a>
					</li>				
					<?
					if($user && $user->isAdmin()) {
					?>	
						<li class="dropdown">
							<a href="#" id="drop1" role='button' class='dropdown-toggle' data-toggle='dropdown'>
								系統維護
								<b class='caret'></b>
							</a>
							<ul class="dropdown-menu" role='menu' aria-labelledby='drop1'>
								<li role='presentation'>
									<a role='menuitem' tabindex="-1" href='<?=Default_Model_Base::WEB_ROOT?>sys/editcode'>編輯代碼</a>
								</li>
								<li role='presentation'>
									<a role='menuitem' tabindex="-1" href='#'>編輯單位</a>
								</li>								
							</ul>
						</li>						
					<?
					}
					?>
				</ul>
			</div>
			            	
			<ul class="nav pull-right">
			  <li id="fat-menu" class="dropdown">
<?
$username = '訪客';
$rolename = '';
if($user) {
	$username = $user->name;
	if($user->isAdmin()) {
		$rolename = '管理者';
	} else if($user->isUser()) {
		$rolename = '使用者';
	}
}
?>			  
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class='icon-user'></i> <?=$username?> <?if($user){?>(<?=$rolename?>)<?}?><b class="caret"></b></a>
			    <ul class="dropdown-menu">
<?
if(!$user) {
?>			    
			      <li><a href="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/login/index">登入</a></li>
<?
} else {
?>
			      <li><a href="<?='/'.Default_Model_Base::WEB_ROOT_TXT?>/login/logout">登出</a></li>
<?
}
?>
			    </ul>
			  </li>
			</ul>          
        </div>
      </div>
    </div>
    
    <div class="container-fluid">

		<div class="row-fluid alert alert-error hide" id="IE_warning">
		此瀏覽器不支援 HTML 5 的功能， 建議使用 <a href="http://moztw.org/" target="_blank">Firefox 10</a> 或 <a href="http://www.google.com.tw/chrome" target="_blank">Google Chrome</a> 以達到最佳使用效果。
		</div>			 

		<?=$this->layout()->content?>
        
		<hr class="soften"/>
		
		<!-- IE 8 畫面會有異常，所以大於 IE 8 以上的 browser 才顯示這段 -->
		<!--[if gt IE 8]><!-->
        <footer class="footer">        
        	<center>
        	&copy; 2013 中華電信數據分公司 南區營運處 系統組 &nbsp;&nbsp;&nbsp;&nbsp;TEL : (04)22531821
        	</center>
        </footer>
        <!--<![endif]-->
	</div>

    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript">
    $(document).ready(function() {     	
        if(!Modernizr.input.required){
            $('#IE_warning').removeClass('hide');
        }
    });
    </script>
</body>
</html>